### ISSUE TITLE
Version Mismatch

### ISSUE THREAD

**Issue by Ayshine** [bitcraze/bitcraze-vm#36]
Hello, 

Is there any specific Oracle VM version I should download? I am getting an error below.
![error_running _vm](https://user-images.githubusercontent.com/28358926/44312366-77ff2d00-a3ff-11e8-8506-2ccaaacb9543.png)
Then I can see a version_mismatch detail below
![version_mismatch](https://user-images.githubusercontent.com/28358926/44312376-89483980-a3ff-11e8-9ac6-0b289e4d6aa8.png)

**Comment by ataffanel** [comment]
This error is not related to the virtual machine but to VirtualBox installation itself, the VirtualBox linux kernel driver is not compiled with the good version. I have had this error before and the way to solve it is usually to restart the computer to make sure you are running the latest kernel and then run ```sudo /sbin/vboxconfig```.

If it does not work and you have installed VirtualBox using the package downloaded from the virtualbox website, you could also try to uninstall it and install it from the Ubuntu repos instead.

Since this is not related to the VM I close this issue, feel free to continue posting on it if you need more help.

**Comment by Ayshine** [comment]
Thank you @ataffanel for your help. I have a couple of other unexpected results on installation steps, so I started from the beginning. Sorry for posting an unrelated issue here. I'll try to reach out from the correct channel.

**Comment by ataffanel** [comment]
No problem, if you still have issues feel free to post on the [Bitcraze forum](https://forum.bitcraze.io).
